version: '3.6'

services:
  namenode:
    build: 
      context: ./docker/namenode
      args:
        - HADOOP_VERSION=3.2.4
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000

  datanode:
    build:
      context: ./docker/datanode
      args:
        - HADOOP_VERSION=3.2.4
    container_name: datanode
    restart: always
    depends_on:
      - namenode