version: '3'

networks:
  hadoop-network:
    driver: bridge

services:
  namenode:
    image: namenode:$HADOOP_VERSION
    build:
      context: ./image/namenode
      args:
        - HADOOP_VERSION=$HADOOP_VERSION
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - hadoop-network

  datanode1:
    image: datanode1:$HADOOP_VERSION
    build: 
      context: ./image/datanode
      args:
        - HADOOP_VERSION=$HADOOP_VERSION
    container_name: datanode1
    restart: always
    depends_on:
      - namenode
    networks:
      - hadoop-network

  datanode2:
    image: datanode2:$HADOOP_VERSION
    build: 
      context: ./image/datanode
      args:
        - HADOOP_VERSION=$HADOOP_VERSION
    container_name: datanode2
    restart: always
    depends_on:
      - namenode
    networks:
      - hadoop-network

  resourcemanager:
    image: resourcemanager:$HADOOP_VERSION
    build: 
      context: ./image/resourcemanager
      args:
        - HADOOP_VERSION=$HADOOP_VERSION
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    networks:
      - hadoop-network

  nodemanager1:
    image: nodemanager1:$HADOOP_VERSION
    build:
      context: ./image/nodemanager
      args:
        - HADOOP_VERSION=$HADOOP_VERSION
    container_name: nodemanager1
    restart: always
    networks:
      - hadoop-network
    depends_on:
      - resourcemanager

  nodemanager2:
    image: nodemanager2:$HADOOP_VERSION
    build:
      context: ./image/nodemanager
      args:
        - HADOOP_VERSION=$HADOOP_VERSION
    container_name: nodemanager2
    restart: always
    networks:
      - hadoop-network
    depends_on:
      - resourcemanager